# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c121186b9b222c2d1d76004e80b33585631f53273924c376f03da7ed5c72e702ce1baead52f86f6580ac9a3cef4bfa9baaf82949356ab8664dd8ac6c6ce38658

test:
  secret_key_base: 7722da8398a3c6130abc20b91998852c0b1b6e0677b852adc23949eeef30560e25da5463fc02af3a613a11f19b58ae3f406df704a45d1aacfb11b965996611e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
